name: podsnap
recipe: lamp
config:
  webroot: 'www'
  php: '8.3'
  via: apache
  ssl: false
  sslExpose: false
proxy:
  appserver:
    - podsnap.lndo.site
services:
  appserver:
    build_as_root:
      - apt-get update && apt-get install vim -y 
